### ISSUE TITLE
Won't compile on ubuntu 15.04

### ISSUE THREAD

**Issue by reemplazable** [holylobster/nuntius-linux#39]
Trying to compile on 15.04 does not compile with this error:
make
XMLLINT not set and xmllint not found in path; skipping xml preprocessing.
XMLLINT not set and xmllint not found in path; skipping xml preprocessing.
  GEN      src/resources.c
XMLLINT not set and xmllint not found in path; skipping xml preprocessing.
git.mk: Generating .gitignore
make  all-recursive
make[1]: Entering directory '/home/jlbarrera/Downloads/nuntius/nuntius-linux'
XMLLINT not set and xmllint not found in path; skipping xml preprocessing.
XMLLINT not set and xmllint not found in path; skipping xml preprocessing.
Making all in po
make[2]: Entering directory '/home/jlbarrera/Downloads/nuntius/nuntius-linux/po'
  MSGFMT de.gmo
  MSGFMT es.gmo
  MSGFMT pl.gmo
  MSGFMT sk.gmo
make[2]: Leaving directory '/home/jlbarrera/Downloads/nuntius/nuntius-linux/po'
make[2]: Entering directory '/home/jlbarrera/Downloads/nuntius/nuntius-linux'
XMLLINT not set and xmllint not found in path; skipping xml preprocessing.
XMLLINT not set and xmllint not found in path; skipping xml preprocessing.
  CC       resources.o
  VALAC    nuntius_vala.stamp
src/notificationsview.vala:35.40-35.56: error: The type name `Gtk.TextViewLayer' could not be found
    protected override void draw_layer(Gtk.TextViewLayer layer, Cairo.Context cr) {
                                       ^^^^^^^^^^^^^^^^^
Compilation failed: 1 error(s), 0 warning(s)
Makefile:853: recipe for target 'nuntius_vala.stamp' failed
make[2]: **\* [nuntius_vala.stamp] Error 1
make[2]: Leaving directory '/home/jlbarrera/Downloads/nuntius/nuntius-linux'
Makefile:948: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/home/jlbarrera/Downloads/nuntius/nuntius-linux'
Makefile:515: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by towo** [comment]
Works when using the GNOME 3.16 (staging IIRC) PPA, FYI.
